### ISSUE TITLE
The Onboarding and Training Epic (FreeCEN)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#825]
- [ ] Review onboarding materials
- [ ] Understand/document onboarding process
- [ ] Document what is needed to complete FC2 onboarding (with as much automation as possible)
- [ ] Make stories within this epic for development
